/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Controle;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Entidade;

/**
 *
 * @author eduardo
 */
public class Tela extends javax.swing.JFrame {

    private List<String> distribuicoesDisponiveis = new ArrayList<>();

    /**
     * Creates new form Tela
     */
    public Tela() {

        initComponents();

        distribuicoesDisponiveis.add("normal(media,desvioPadrao)");
        distribuicoesDisponiveis.add("expo(media)");
        distribuicoesDisponiveis.add("uniforme(minimo,maximo)");
        
        this.tabelaDados.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        String toolTip = "";
        for(String str: distribuicoesDisponiveis) {
            toolTip += str+"   ";
        }
        inTEC.setToolTipText(toolTip);
        inTS.setToolTipText(toolTip);
        
        ButtonGroup radioGroup = new ButtonGroup();
        radioGroup.add(this.radioComAnimacao);
        radioGroup.add(this.radioSemAnimacao);
        radioSemAnimacao.setSelected(true);
    }

    public void adicionarListenerBotaoExecutar(ActionListener listener) {
        this.botaoExecutar.addActionListener(listener);
    }
    
    public List<String> getCampos() {
        
        String tipoTEC = (String) this.comboTEC.getModel().getSelectedItem();
        String valorTEC = inTEC.getText();
        String tipoTS = (String) this.comboTS.getModel().getSelectedItem();
        String valorTS = inTS.getText();
        String tempoSimulacao = inTempoSimuacao.getText();
        
        List<String> retorno = new ArrayList<>();
        
        retorno.add(tipoTEC);
        retorno.add(valorTEC);
        retorno.add(tipoTS);
        retorno.add(valorTS);
        retorno.add(tempoSimulacao);
        
        return retorno;
        
    }
    
    public void exibirMensagem(String msg, String titulo) {
        JOptionPane.showMessageDialog(this, msg, titulo, JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelEntrada = new javax.swing.JPanel();
        comboTEC = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inTEC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboTS = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        inTS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inTempoSimuacao = new javax.swing.JTextField();
        botaoExecutar = new javax.swing.JButton();
        radioComAnimacao = new javax.swing.JRadioButton();
        radioSemAnimacao = new javax.swing.JRadioButton();
        painelAnimacao = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDados = new javax.swing.JTable();
        painelSaida = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        outNumeroMedioEntidadesFila = new javax.swing.JLabel();
        outTaxaMediaOcupacaoServidor = new javax.swing.JLabel();
        outTempoMedioEntidadeFila = new javax.swing.JLabel();
        outTempoMedioSistema = new javax.swing.JLabel();
        outContadorEntidades = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador");
        setName("Tela"); // NOI18N

        painelEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder("Entradas"));

        comboTEC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Determinístico", "Aleatório" }));

        jLabel1.setText("TEC:");

        jLabel2.setText("Valor:");

        jLabel3.setText("TS:");

        comboTS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Determinístico", "Aleatório" }));

        jLabel4.setText("Valor:");

        jLabel5.setText("Tempo de Simulação:");

        botaoExecutar.setText("Executar");

        radioComAnimacao.setText("com Animação");

        radioSemAnimacao.setText("sem Animação");

        javax.swing.GroupLayout painelEntradaLayout = new javax.swing.GroupLayout(painelEntrada);
        painelEntrada.setLayout(painelEntradaLayout);
        painelEntradaLayout.setHorizontalGroup(
            painelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEntradaLayout.createSequentialGroup()
                        .addGroup(painelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(painelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTEC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEntradaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inTEC))
                            .addGroup(painelEntradaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inTS))))
                    .addGroup(painelEntradaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inTempoSimuacao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEntradaLayout.createSequentialGroup()
                        .addComponent(radioComAnimacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioSemAnimacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoExecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelEntradaLayout.setVerticalGroup(
            painelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEntradaLayout.createSequentialGroup()
                .addGroup(painelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboTEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(inTEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(inTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inTempoSimuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExecutar)
                    .addComponent(radioComAnimacao)
                    .addComponent(radioSemAnimacao)))
        );

        painelAnimacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Ilustração fila"));

        javax.swing.GroupLayout painelAnimacaoLayout = new javax.swing.GroupLayout(painelAnimacao);
        painelAnimacao.setLayout(painelAnimacaoLayout);
        painelAnimacaoLayout.setHorizontalGroup(
            painelAnimacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        painelAnimacaoLayout.setVerticalGroup(
            painelAnimacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        tabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entidade", "Relógio", "TEC", "TS", "T. na Fila", "T. Inicio Atend.", "T. Final Atend.", "T. no sistema", "T. Livre Oper."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaDados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        painelSaida.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jLabel6.setText("Número médio de entidades na fila: ");

        jLabel7.setText("Taxa média de ocupação do servidor: ");

        jLabel8.setText("Tempo médio de uma entidade na fila:");

        jLabel9.setText("Tempo médio no sistema:");

        jLabel10.setText("Contador de entidades:");

        javax.swing.GroupLayout painelSaidaLayout = new javax.swing.GroupLayout(painelSaida);
        painelSaida.setLayout(painelSaidaLayout);
        painelSaidaLayout.setHorizontalGroup(
            painelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSaidaLayout.createSequentialGroup()
                        .addGroup(painelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(22, 22, 22)
                        .addGroup(painelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outNumeroMedioEntidadesFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outTempoMedioEntidadeFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outTempoMedioSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outContadorEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(painelSaidaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(outTaxaMediaOcupacaoServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelSaidaLayout.setVerticalGroup(
            painelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSaidaLayout.createSequentialGroup()
                .addGroup(painelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outNumeroMedioEntidadesFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(outTaxaMediaOcupacaoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(painelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(outTempoMedioEntidadeFila, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(outTempoMedioSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outContadorEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelAnimacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(painelSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelAnimacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(painelSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExecutar;
    private javax.swing.JComboBox comboTEC;
    private javax.swing.JComboBox comboTS;
    private javax.swing.JTextField inTEC;
    private javax.swing.JTextField inTS;
    private javax.swing.JTextField inTempoSimuacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel outContadorEntidades;
    private javax.swing.JLabel outNumeroMedioEntidadesFila;
    private javax.swing.JLabel outTaxaMediaOcupacaoServidor;
    private javax.swing.JLabel outTempoMedioEntidadeFila;
    private javax.swing.JLabel outTempoMedioSistema;
    private javax.swing.JPanel painelAnimacao;
    private javax.swing.JPanel painelEntrada;
    private javax.swing.JPanel painelSaida;
    private javax.swing.JRadioButton radioComAnimacao;
    private javax.swing.JRadioButton radioSemAnimacao;
    private javax.swing.JTable tabelaDados;
    // End of variables declaration//GEN-END:variables

    
    public void setResultado(double numeroMedioEntidadesFila,
            double taxaMediaOcupacaoServidor,double tempoMedioEntidadeFila,
            double tempoMedioSistema,int contadorEntidades) {
        
        DecimalFormat df = new DecimalFormat("#.##");
        this.outNumeroMedioEntidadesFila.setText(df.format(numeroMedioEntidadesFila));
        this.outTaxaMediaOcupacaoServidor.setText( df.format(taxaMediaOcupacaoServidor*100)+" %" );
        this.outTempoMedioEntidadeFila.setText(df.format(tempoMedioEntidadeFila));
        this.outTempoMedioSistema.setText(df.format(tempoMedioSistema));
        this.outContadorEntidades.setText(  Integer.toString(contadorEntidades) );

    }

    public void adicionarEntidadeTabela(Entidade entidade) {
        DefaultTableModel modeloTabela = (DefaultTableModel) this.tabelaDados.getModel();
        
        Object[] linha = {entidade.getNumeroEntidade(),entidade.getTempoChegadaSistema(),
            entidade.getTempoEntreChegadas(),entidade.getTempoServico(),
            entidade.getTempoFila(),entidade.getTempoInicioAtendimento(),
            entidade.getTempoFinalAtendimento(),entidade.getTempoClienteSistema(),
            entidade.getTempoLivreOperador()
        };
        
        modeloTabela.addRow(linha);
    }

    public int getQtdLinhasTabela() {
        return this.tabelaDados.getRowCount();
    }
    
    public void limparTabela() {
        
        ((DefaultTableModel)this.tabelaDados.getModel()).setRowCount(0);
    }

    public void updateAnimacao(int contadorEntidadesNaFila) {
        
        if(this.radioComAnimacao.isSelected()) {
            Graphics graphics = this.painelAnimacao.getGraphics();
            
            
            int width = this.painelAnimacao.getWidth();
            int height = this.painelAnimacao.getHeight();
            
            try {
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                Logger.getLogger(Controle.class.getName()).log(Level.SEVERE, null, ex);
            }
            graphics.clearRect(10, 20, width-20, height-50);

            graphics.setColor(Color.BLACK);
            
            if(contadorEntidadesNaFila == -1) {
                contadorEntidadesNaFila = 0;
            }
            
            graphics.drawString("Quantidade na fila: "+contadorEntidadesNaFila, 30, 30);
            
            graphics.setColor(Color.RED);
        
            int posX = width - 20;
            int posY = height - 40;

            for(int i = 0; i < contadorEntidadesNaFila; i++) {
                graphics.fillOval(posX, posY, 8, 8);
                graphics.drawOval(posX, posY, 8, 8);

                posX -= 10;

                if(posX <= 10) {
                    posX = width - 20;
                    posY -= 10;
                }
            }
        }

    }
    
    
}
